/**
 * dxvk.conf Parser and Generator
 *
 * Parses and generates DXVK configuration files.
 *
 * @see https://github.com/doitsujin/dxvk/blob/master/dxvk.conf
 */

import { readFile, writeFile, access, constants } from 'fs/promises'
import { join } from 'path'

export interface DxvkConfig {
  // Frame rate limiting
  'dxgi.maxFrameRate'?: number
  'd3d9.maxFrameRate'?: number

  // Memory management
  'dxgi.maxDeviceMemory'?: number
  'd3d9.maxAvailableMemory'?: number

  // HUD options
  'dxvk.hud'?: string

  // Async/GPL options
  'dxvk.enableAsync'?: boolean
  'dxvk.gplAsyncCache'?: boolean

  // Latency
  'dxvk.latencySleep'?: boolean

  // Device spoofing
  'dxgi.customVendorId'?: string
  'dxgi.customDeviceId'?: string
  'dxgi.customDeviceDesc'?: string

  // HDR
  'dxgi.enableHDR'?: boolean

  // Tear-free
  'dxvk.tearFree'?: 'auto' | 'true' | 'false'

  // D3D9 specific
  'd3d9.forceSwapchainMSAA'?: number
  'd3d9.samplerAnisotropy'?: number

  // Other options (catch-all)
  [key: string]: string | number | boolean | undefined
}

// Default configuration
export const DEFAULT_CONFIG: DxvkConfig = {
  'dxvk.hud': 'fps,frametimes',
}

/**
 * Parse a dxvk.conf file
 */
export async function parseConfig(configPath: string): Promise<DxvkConfig> {
  try {
    await access(configPath, constants.R_OK)
    const content = await readFile(configPath, 'utf-8')
    return parseConfigContent(content)
  } catch {
    return { ...DEFAULT_CONFIG }
  }
}

/**
 * Parse config content string
 */
export function parseConfigContent(content: string): DxvkConfig {
  const config: DxvkConfig = {}
  const lines = content.split('\n')

  for (const line of lines) {
    const trimmed = line.trim()

    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('//')) {
      continue
    }

    // Parse key = value
    const match = trimmed.match(/^([a-zA-Z0-9_.]+)\s*=\s*(.+)$/)
    if (match) {
      const [, key, rawValue] = match
      const value = rawValue.trim()

      // Parse value type
      if (value === 'True' || value === 'true') {
        config[key] = true
      } else if (value === 'False' || value === 'false') {
        config[key] = false
      } else if (/^\d+$/.test(value)) {
        config[key] = parseInt(value, 10)
      } else {
        config[key] = value
      }
    }
  }

  return config
}

/**
 * Generate dxvk.conf content from config object
 */
export function generateConfigContent(config: DxvkConfig): string {
  const lines: string[] = [
    '# DXVK Configuration',
    '# Generated by DXVK Studio',
    '# https://github.com/Zendevve/dxvk-studio',
    '',
  ]

  // Group options by category
  const categories: Record<string, string[]> = {
    'Frame Rate': ['dxgi.maxFrameRate', 'd3d9.maxFrameRate'],
    'Memory': ['dxgi.maxDeviceMemory', 'd3d9.maxAvailableMemory'],
    'HUD': ['dxvk.hud'],
    'Async': ['dxvk.enableAsync', 'dxvk.gplAsyncCache'],
    'Latency': ['dxvk.latencySleep'],
    'Device': ['dxgi.customVendorId', 'dxgi.customDeviceId', 'dxgi.customDeviceDesc'],
    'Display': ['dxgi.enableHDR', 'dxvk.tearFree'],
    'D3D9': ['d3d9.forceSwapchainMSAA', 'd3d9.samplerAnisotropy'],
  }

  const usedKeys = new Set<string>()

  for (const [category, keys] of Object.entries(categories)) {
    const categoryLines: string[] = []

    for (const key of keys) {
      if (config[key] !== undefined) {
        const value = formatValue(config[key])
        categoryLines.push(`${key} = ${value}`)
        usedKeys.add(key)
      }
    }

    if (categoryLines.length > 0) {
      lines.push(`# ${category}`)
      lines.push(...categoryLines)
      lines.push('')
    }
  }

  // Add any remaining keys not in categories
  const otherKeys = Object.keys(config).filter(k => !usedKeys.has(k) && config[k] !== undefined)
  if (otherKeys.length > 0) {
    lines.push('# Other')
    for (const key of otherKeys) {
      lines.push(`${key} = ${formatValue(config[key])}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Format a config value for writing
 */
function formatValue(value: string | number | boolean | undefined): string {
  if (typeof value === 'boolean') {
    return value ? 'True' : 'False'
  }
  return String(value)
}

/**
 * Save config to a game directory
 */
export async function saveConfig(gamePath: string, config: DxvkConfig): Promise<void> {
  const configPath = join(gamePath, 'dxvk.conf')
  const content = generateConfigContent(config)
  await writeFile(configPath, content, 'utf-8')
}

/**
 * Load config from a game directory
 */
export async function loadConfig(gamePath: string): Promise<DxvkConfig> {
  const configPath = join(gamePath, 'dxvk.conf')
  return parseConfig(configPath)
}

/**
 * Get HUD options as array
 */
export function parseHudOptions(hudString: string): string[] {
  if (!hudString) return []
  return hudString.split(',').map(s => s.trim()).filter(Boolean)
}

/**
 * Join HUD options into string
 */
export function formatHudOptions(options: string[]): string {
  return options.join(',')
}

// Available HUD options
export const HUD_OPTIONS = [
  { key: 'devinfo', label: 'Device Info', description: 'GPU name, driver version' },
  { key: 'fps', label: 'FPS', description: 'Frames per second' },
  { key: 'frametimes', label: 'Frame Times', description: 'Frame time graph' },
  { key: 'submissions', label: 'Submissions', description: 'Command buffer submissions' },
  { key: 'drawcalls', label: 'Draw Calls', description: 'Number of draw calls' },
  { key: 'pipelines', label: 'Pipelines', description: 'Pipeline count' },
  { key: 'descriptors', label: 'Descriptors', description: 'Descriptor pool usage' },
  { key: 'memory', label: 'Memory', description: 'Memory allocation info' },
  { key: 'gpuload', label: 'GPU Load', description: 'GPU utilization' },
  { key: 'version', label: 'Version', description: 'DXVK version' },
  { key: 'api', label: 'API', description: 'D3D API version' },
  { key: 'cs', label: 'Compiler', description: 'Shader compiler activity' },
  { key: 'compiler', label: 'Compiler (Full)', description: 'Full compiler info' },
]

// Vendor IDs for spoofing
export const VENDOR_IDS = [
  { id: '0x10de', name: 'NVIDIA' },
  { id: '0x1002', name: 'AMD' },
  { id: '0x8086', name: 'Intel' },
]
